/*Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference is pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
*/
def MAX() {5000}

def prob044(){
	list = findPents()
	
}

def findPents(){
	list = new ArrayList()
	for (n in 1..MAX()){
		list << (n*(3*n-1)/2)}
	list
}


println(findPents())


/*
	n(3n-1)/2 + (n+1)(3n+2)/2 = x(3x-1)/2
	(3n^-n+3n^+2n+3n+2)/2
	6n^+4n+2
*/