/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

def prob002a(){
    i=1
    j=2
    sum = 2
    while ((2*i + 3*j )<4000000)
    {
        k = 2*i+3*j
        i = i+2*j
        j=k
        sum+=k
    }
    println sum
}

//an alternate solution
def prob002b(){
    i = 1
    j = 1
    sum = 0
    while (i+j<4000000) 
    {
        k=i+j
        if (k%2==0)
            sum+=k
        i=j
        j=k
    }
    println sum
}
